// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Blog Article → Tags*
 */
export interface BlogArticleDocumentDataTagsItem {
  /**
   * Tag field in *Blog Article → Tags*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blogArticle.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tag: prismic.ContentRelationshipField<"blogTag">;
}

type BlogArticleDocumentDataSlices3Slice = TextBlockSlice | ImageBlockSlice;

/**
 * Content for Blog Article documents
 */
interface BlogArticleDocumentData {
  /**
   * Title field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogArticle.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date Posted field in *Blog Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogArticle.datePosted
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  datePosted: prismic.DateField
  /**
   * Meta Description field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogArticle.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogArticle.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<"card">
  /**
   * Tags field in *Blog Article*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogArticle.tags[]
   * - **Tab**: Tags
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  tags: prismic.GroupField<Simplify<BlogArticleDocumentDataTagsItem>>
  /**
   * Slice Zone field in *Blog Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogArticle.slices3[]
   * - **Tab**: Article
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<BlogArticleDocumentDataSlices3Slice>;
}

/**
 * Blog Article document from Prismic
 *
 * - **API ID**: `blogArticle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogArticleDocumentData>,
    "blogArticle",
    Lang
  >;

/**
 * Item in *Blog Index Page → Tags*
 */
export interface BlogIndexDocumentDataBlogTagsItem {
  /**
   * Blog Tag field in *Blog Index Page → Tags*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blogIndex.blogTags[].blogTag
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blogTag: prismic.ContentRelationshipField<"blogTag">;
}

/**
 * Content for Blog Index Page documents
 */
interface BlogIndexDocumentData {
  /**
   * Title field in *Blog Index Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogIndex.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
  /**
   * Meta Description field in *Blog Index Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogIndex.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Index Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogIndex.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never>
  /**
   * Intro field in *Blog Index Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Introduction text that appears above the blogs list
   * - **API ID Path**: blogIndex.intro
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  intro: prismic.RichTextField
  /**
   * Tags field in *Blog Index Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogIndex.blogTags[]
   * - **Tab**: Filters
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  blogTags: prismic.GroupField<Simplify<BlogIndexDocumentDataBlogTagsItem>>;
}

/**
 * Blog Index Page document from Prismic
 *
 * - **API ID**: `blogIndex`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogIndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogIndexDocumentData>,
    "blogIndex",
    Lang
  >;

/**
 * Content for Blog Tag documents
 */
interface BlogTagDocumentData {
  /**
   * Title field in *Blog Tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogTag.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Blog Tag document from Prismic
 *
 * - **API ID**: `blogTag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogTagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogTagDocumentData>,
    "blogTag",
    Lang
  >;

type ContentPageDocumentDataSlicesSlice = ImageBlockSlice | TextBlockSlice;

/**
 * Content for Content Page documents
 */
interface ContentPageDocumentData {
  /**
   * Title field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
  /**
   * Meta Description field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contentPage.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *Content Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never>
  /**
   * Slice Zone field in *Content Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contentPage.slices[]
   * - **Tab**: Article
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices: prismic.SliceZone<ContentPageDocumentDataSlicesSlice>;
}

/**
 * Content Page document from Prismic
 *
 * - **API ID**: `contentPage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentPageDocumentData>,
    "contentPage",
    Lang
  >;

/**
 * Item in *Globals → Social Links*
 */
export interface GlobalsDocumentDataSocialLinksItem {
  /**
   * Platform field in *Globals → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Instagram
   * - **API ID Path**: globals.socialLinks[].platform
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  platform: prismic.SelectField<
    "Instagram" | "Twitter" | "Facebook" | "Linkedin",
    "filled"
  >;

  /**
   * Link field in *Globals → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.socialLinks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Globals documents
 */
interface GlobalsDocumentData {
  /**
   * Social Links field in *Globals*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.socialLinks[]
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socialLinks: prismic.GroupField<Simplify<GlobalsDocumentDataSocialLinksItem>>
  /**
   * Address field in *Globals*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  contactAddress: prismic.RichTextField;

  /**
   * Location field in *Globals*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactLocation
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  contactLocation: prismic.GeoPointField;

  /**
   * Map Link field in *Globals*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactMapLink
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contactMapLink: prismic.LinkField;

  /**
   * Email Address field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactEmailAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contactEmailAddress: prismic.KeyTextField;

  /**
   * Telephone Number field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactNumber
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contactNumber: prismic.KeyTextField;
}

/**
 * Globals document from Prismic
 *
 * - **API ID**: `globals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalsDocumentData>,
    "globals",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = ImageBlockSlice | TextBlockSlice;

/**
 * Item in *Homepage → Page Links*
 */
export interface HomepageDocumentDataPageLinksItem {
  /**
   * Link field in *Homepage → Page Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.pageLinks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<"contentPage">;
}

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never>
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Article
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Page Links field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.pageLinks[]
   * - **Tab**: Links
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  pageLinks: prismic.GroupField<Simplify<HomepageDocumentDataPageLinksItem>>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Legal Page documents
 */
interface LegalPageDocumentData {
  /**
   * Title field in *Legal Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legalPage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
  /**
   * Meta Description field in *Legal Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legalPage.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *Legal Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legalPage.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never>
  /**
   * Body field in *Legal Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legalPage.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  body: prismic.RichTextField;
}

/**
 * Legal Page document from Prismic
 *
 * - **API ID**: `legalPage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LegalPageDocumentData>,
    "legalPage",
    Lang
  >;

/**
 * Item in *Site Footer → Menu Items*
 */
export interface SiteFooterDocumentDataMenuItemsItem {
  /**
   * Link field in *Site Footer → Menu Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: siteFooter.menuItems[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField;

  /**
   * Label field in *Site Footer → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: siteFooter.menuItems[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Site Footer documents
 */
interface SiteFooterDocumentData {
  /**
   * Menu Items field in *Site Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: siteFooter.menuItems[]
   * - **Tab**: Menu
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menuItems: prismic.GroupField<Simplify<SiteFooterDocumentDataMenuItemsItem>>;
}

/**
 * Site Footer document from Prismic
 *
 * - **API ID**: `siteFooter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteFooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteFooterDocumentData>,
    "siteFooter",
    Lang
  >;

/**
 * Item in *Site Header → Menu Items*
 */
export interface SiteHeaderDocumentDataMenuItemsItem {
  /**
   * Link field in *Site Header → Menu Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: siteHeader.menuItems[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField;

  /**
   * Label field in *Site Header → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: siteHeader.menuItems[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Site Header documents
 */
interface SiteHeaderDocumentData {
  /**
   * Menu Items field in *Site Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: siteHeader.menuItems[]
   * - **Tab**: Menu
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menuItems: prismic.GroupField<Simplify<SiteHeaderDocumentDataMenuItemsItem>>;
}

/**
 * Site Header document from Prismic
 *
 * - **API ID**: `siteHeader`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteHeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteHeaderDocumentData>,
    "siteHeader",
    Lang
  >;

export type AllDocumentTypes =
  | BlogArticleDocument
  | BlogIndexDocument
  | BlogTagDocument
  | ContentPageDocument
  | GlobalsDocument
  | HomepageDocument
  | LegalPageDocument
  | SiteFooterDocument
  | SiteHeaderDocument;

/**
 * Primary content in *Image Block → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
  /**
   * Image field in *Image Block → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"SmallScreen">;

  /**
   * Caption field in *Image Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional caption for the image
   * - **API ID Path**: image_block.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for Image Block Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image Block → Primary*
 */
export interface ImageBlockSliceImageBlockFullScreenPrimary {
  /**
   * Image field in *Image Block → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"wide" | "square" | "portrait">;

  /**
   * Caption field in *Image Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional caption for the image
   * - **API ID Path**: image_block.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Image Block - Full Screen variation for Image Block Slice
 *
 * - **API ID**: `imageBlockFullScreen`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceImageBlockFullScreen = prismic.SharedSliceVariation<
  "imageBlockFullScreen",
  Simplify<ImageBlockSliceImageBlockFullScreenPrimary>,
  never
>;

/**
 * Slice variation for *Image Block*
 */
type ImageBlockSliceVariation =
  | ImageBlockSliceDefault
  | ImageBlockSliceImageBlockFullScreen;

/**
 * Image Block Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: Image Block
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSlice = prismic.SharedSlice<
  "image_block",
  ImageBlockSliceVariation
>;

/**
 * Primary content in *Text Block → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Heading field in *Text Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Text Block → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Text Block Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text Block → Primary*
 */
export interface TextBlockSliceTextBlockWithCtaPrimary {
  /**
   * Heading field in *Text Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Text Block → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * CTA Link field in *Text Block → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctaLink: prismic.LinkField;

  /**
   * CTA Label field in *Text Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ctaLabel: prismic.KeyTextField;
}

/**
 * Text Block with CTA variation for Text Block Slice
 *
 * - **API ID**: `textBlockWithCta`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceTextBlockWithCta = prismic.SharedSliceVariation<
  "textBlockWithCta",
  Simplify<TextBlockSliceTextBlockWithCtaPrimary>,
  never
>;

/**
 * Slice variation for *Text Block*
 */
type TextBlockSliceVariation =
  | TextBlockSliceDefault
  | TextBlockSliceTextBlockWithCta;

/**
 * Text Block Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: Text Block
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogArticleDocument,
      BlogArticleDocumentData,
      BlogArticleDocumentDataTagsItem,
      BlogArticleDocumentDataSlices3Slice,
      BlogIndexDocument,
      BlogIndexDocumentData,
      BlogIndexDocumentDataBlogTagsItem,
      BlogTagDocument,
      BlogTagDocumentData,
      ContentPageDocument,
      ContentPageDocumentData,
      ContentPageDocumentDataSlicesSlice,
      GlobalsDocument,
      GlobalsDocumentData,
      GlobalsDocumentDataSocialLinksItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocumentDataPageLinksItem,
      LegalPageDocument,
      LegalPageDocumentData,
      SiteFooterDocument,
      SiteFooterDocumentData,
      SiteFooterDocumentDataMenuItemsItem,
      SiteHeaderDocument,
      SiteHeaderDocumentData,
      SiteHeaderDocumentDataMenuItemsItem,
      AllDocumentTypes,
      ImageBlockSlice,
      ImageBlockSliceDefaultPrimary,
      ImageBlockSliceImageBlockFullScreenPrimary,
      ImageBlockSliceVariation,
      ImageBlockSliceDefault,
      ImageBlockSliceImageBlockFullScreen,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceTextBlockWithCtaPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextBlockSliceTextBlockWithCta,
    };
  }
}
