// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Globals documents
 */
interface GlobalsDocumentData {
  /**
   * LinkedIn field in *Globals*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.linkedInLink
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedInLink: prismic.LinkField /**
   * Email Address field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactEmailAddress
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  contactEmailAddress: prismic.KeyTextField;

  /**
   * Telephone Number field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.contactNumber
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contactNumber: prismic.KeyTextField;
}

/**
 * Globals document from Prismic
 *
 * - **API ID**: `globals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalsDocumentData>,
    "globals",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = ImageBlockSlice | TextBlockSlice;

/**
 * Item in *[PAGE] Homepage → Projects*
 */
export interface HomepageDocumentDataProjectsItem {
  /**
   * Project field in *[PAGE] Homepage → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

/**
 * Content for [PAGE] Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *[PAGE] Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField /**
   * Meta Description field in *[PAGE] Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *[PAGE] Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never> /**
   * Slice Zone field in *[PAGE] Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Article
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Projects field in *[PAGE] Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.projects[]
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  projects: prismic.GroupField<Simplify<HomepageDocumentDataProjectsItem>>;
}

/**
 * [PAGE] Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for [PAGE] Legal Page documents
 */
interface LegalPageDocumentData {
  /**
   * Title field in *[PAGE] Legal Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legalPage.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField /**
   * Meta Description field in *[PAGE] Legal Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legalPage.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *[PAGE] Legal Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legalPage.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never> /**
   * Body field in *[PAGE] Legal Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legalPage.body
   * - **Tab**: Body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  body: prismic.RichTextField;
}

/**
 * [PAGE] Legal Page document from Prismic
 *
 * - **API ID**: `legalPage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LegalPageDocumentData>,
    "legalPage",
    Lang
  >;

/**
 * Item in *[PAGE] Project → Credits*
 */
export interface ProjectDocumentDataCreditsItem {
  /**
   * Heading field in *[PAGE] Project → Credits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.credits[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Credit field in *[PAGE] Project → Credits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.credits[].credit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  credit: prismic.KeyTextField;
}

/**
 * Item in *[PAGE] Project → Tech*
 */
export interface ProjectDocumentDataTechItem {
  /**
   * Item field in *[PAGE] Project → Tech*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.tech[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;
}

type ProjectDocumentDataSlices3Slice = TextBlockSlice | ImageBlockSlice;

/**
 * Content for [PAGE] Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *[PAGE] Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField /**
   * Meta Description field in *[PAGE] Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *[PAGE] Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<"card"> /**
   * Hero Image field in *[PAGE] Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.heroImage
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  heroImage: prismic.ImageField<"portrait"> /**
   * Project Link field in *[PAGE] Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.projectLink
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  projectLink: prismic.LinkField;

  /**
   * Credits field in *[PAGE] Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.credits[]
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  credits: prismic.GroupField<Simplify<ProjectDocumentDataCreditsItem>>;

  /**
   * Tech field in *[PAGE] Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.tech[]
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tech: prismic.GroupField<Simplify<ProjectDocumentDataTechItem>> /**
   * Intro field in *[PAGE] Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.intro
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  intro: prismic.RichTextField /**
   * Slice Zone field in *[PAGE] Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices3[]
   * - **Tab**: Article
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<ProjectDocumentDataSlices3Slice>;
}

/**
 * [PAGE] Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Content for [PAGE] Project Index documents
 */
interface ProjectIndexDocumentData {
  /**
   * Title field in *[PAGE] Project Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projectIndex.title
   * - **Tab**: Core
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField /**
   * Meta Description field in *[PAGE] Project Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projectIndex.metaDescription
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metaDescription: prismic.KeyTextField;

  /**
   * Meta Image field in *[PAGE] Project Index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projectIndex.metaImage
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metaImage: prismic.ImageField<never> /**
   * Intro field in *[PAGE] Project Index*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Introduction text that appears above the projects list
   * - **API ID Path**: projectIndex.intro
   * - **Tab**: Intro
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  intro: prismic.RichTextField;
}

/**
 * [PAGE] Project Index document from Prismic
 *
 * - **API ID**: `projectIndex`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectIndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectIndexDocumentData>,
    "projectIndex",
    Lang
  >;

/**
 * Item in *Site Footer → Menu Items*
 */
export interface SiteFooterDocumentDataMenuItemsItem {
  /**
   * Link field in *Site Footer → Menu Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: siteFooter.menuItems[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField;

  /**
   * Label field in *Site Footer → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: siteFooter.menuItems[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Site Footer documents
 */
interface SiteFooterDocumentData {
  /**
   * Menu Items field in *Site Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: siteFooter.menuItems[]
   * - **Tab**: Menu
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menuItems: prismic.GroupField<Simplify<SiteFooterDocumentDataMenuItemsItem>>;
}

/**
 * Site Footer document from Prismic
 *
 * - **API ID**: `siteFooter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteFooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteFooterDocumentData>,
    "siteFooter",
    Lang
  >;

export type AllDocumentTypes =
  | GlobalsDocument
  | HomepageDocument
  | LegalPageDocument
  | ProjectDocument
  | ProjectIndexDocument
  | SiteFooterDocument;

/**
 * Primary content in *Image Block → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
  /**
   * Image field in *Image Block → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"SmallScreen">;

  /**
   * Caption field in *Image Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional caption for the image
   * - **API ID Path**: image_block.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for Image Block Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image Block → Primary*
 */
export interface ImageBlockSliceImageBlockFullScreenPrimary {
  /**
   * Image field in *Image Block → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"wide" | "square" | "portrait">;

  /**
   * Caption field in *Image Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional caption for the image
   * - **API ID Path**: image_block.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Image Block - Full Screen variation for Image Block Slice
 *
 * - **API ID**: `imageBlockFullScreen`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceImageBlockFullScreen = prismic.SharedSliceVariation<
  "imageBlockFullScreen",
  Simplify<ImageBlockSliceImageBlockFullScreenPrimary>,
  never
>;

/**
 * Slice variation for *Image Block*
 */
type ImageBlockSliceVariation =
  | ImageBlockSliceDefault
  | ImageBlockSliceImageBlockFullScreen;

/**
 * Image Block Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: Image Block
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSlice = prismic.SharedSlice<
  "image_block",
  ImageBlockSliceVariation
>;

/**
 * Primary content in *Text Block → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Heading field in *Text Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Text Block → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Text Block Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text Block → Primary*
 */
export interface TextBlockSliceTextBlockWithCtaPrimary {
  /**
   * Heading field in *Text Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Text Block → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * CTA Link field in *Text Block → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctaLink: prismic.LinkField;

  /**
   * CTA Label field in *Text Block → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ctaLabel: prismic.KeyTextField;
}

/**
 * Text Block with CTA variation for Text Block Slice
 *
 * - **API ID**: `textBlockWithCta`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceTextBlockWithCta = prismic.SharedSliceVariation<
  "textBlockWithCta",
  Simplify<TextBlockSliceTextBlockWithCtaPrimary>,
  never
>;

/**
 * Slice variation for *Text Block*
 */
type TextBlockSliceVariation =
  | TextBlockSliceDefault
  | TextBlockSliceTextBlockWithCta;

/**
 * Text Block Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: Text Block
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GlobalsDocument,
      GlobalsDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocumentDataProjectsItem,
      LegalPageDocument,
      LegalPageDocumentData,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataCreditsItem,
      ProjectDocumentDataTechItem,
      ProjectDocumentDataSlices3Slice,
      ProjectIndexDocument,
      ProjectIndexDocumentData,
      SiteFooterDocument,
      SiteFooterDocumentData,
      SiteFooterDocumentDataMenuItemsItem,
      AllDocumentTypes,
      ImageBlockSlice,
      ImageBlockSliceDefaultPrimary,
      ImageBlockSliceImageBlockFullScreenPrimary,
      ImageBlockSliceVariation,
      ImageBlockSliceDefault,
      ImageBlockSliceImageBlockFullScreen,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceTextBlockWithCtaPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextBlockSliceTextBlockWithCta,
    };
  }
}
