// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from 'vue'
import { defineSliceZoneComponents } from '@prismicio/vue'

export const components = defineSliceZoneComponents({
  image_block: defineAsyncComponent(
    () => import('./ImageBlock/index.vue'),
  ),
  text_block: defineAsyncComponent(() => import('./TextBlock/index.vue')),
})
