// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  text_and_media: defineAsyncComponent(
    () => import("./TextMediaBlock/index.vue"),
  ),
  text_block: defineAsyncComponent(() => import("./TextBlock/index.vue")),
  video_block: defineAsyncComponent(() => import("./VideoBlock/index.vue")),
  carousel_block: defineAsyncComponent(
    () => import("./CarouselBlock/index.vue"),
  ),
});
